server:
  affinity: ""
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      config: |
          ui = true
          cluster_name = "vault-transit"
          storage "raft" {
             path  = "/vault/data/"
          }

          listener "tcp" {
             address = "0.0.0.0:8200"
             cluster_address = "0.0.0.0:8201"
             tls_disable = "true"
          }

  dataStorage:
    enabled: true

  auditStorage:
    enabled: true

global:
  enabled: true
  namespace: 'vault-transit'
  tlsDisable: true # updated to enable TLS

injector:
  enabled: false
